Feature/setup
jdmartinez1062/calculator pull request #1
Opened 2021-05-16 20:08 UTC by jdmartinez1062

Completed React app setup using npm. Deployed the app to heroku.

2021-05-16 23:22 UTC, Forison requested changes
#### Invalid❕❕

##### You need to enable linter checks on this or before it can be review. This would be marked invalid. Kindly address the issue and submit a re-review

#### Happy coding
Addo Forison

2021-05-17 04:35 UTC, bellom requested changes
## Hi @jdmartinez1062  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2021-05-17 04:35 UTC, bellom commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
**Kindly update your `README` file**
**Let's make your repo look more professional by updating your `README` file**.
Checkout out the below link for help, feel free to follow this [Microverse template](https://github.com/microverseinc/readme-template) from pathwright

2021-05-24 06:46 UTC, mikenath223 requested changes
### Hello @jdmartinez1062 👋

**You've done pretty well here fixing a few issues raised in the previous review. 👌**

However, let's make a couple of changes.

- Please refer to comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-24 06:47 UTC, mikenath223 commented on README.md
> +
- [ ] Kindly deploy the project online and include the live link in the readme.

2021-05-29 03:48 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @jdmartinez1062,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Dipesh Kumar_**

2021-06-07 02:24 UTC, closed without merging